def usage():
    print()
    print("===============================================================================")
    print("optool - dust opacities from the command line")
    print("         Dominik, Min, Tazaki 2021, https://ascl.net/2104.010, version 1.9.14")
    print()
    print("-c                        List available materials")
    print("-c KEY-or-FILE [Mfrac]    Add material with mass fraction. -c may be omitted")
    print("-m KEY-or-FILE [Mfrac]    Add material with mass fraction in mantle")
    print("-p POROSITY [PMANTLE]     Set porosity, possibly different for core and mantle")
    print("-dhs [FMAX]               Maximum volume fraction of vacuum in DHS computation")
    print("-mmf [A0 [DF-or-FILL]]    Use MMF with monomer size A0 and fractal dim or fill")
    print("-a AMIN [AMAX [SD [NA]]]  Grain size [micron] dist. SD=P (>PL) or M:S (>log-n)")
    print("-l LMIN [LMAX [NLAM]]     Set up wavelength grid  (units for a and l: microns)")
    print("-a FILE; -l FILE          Read size distribution or lambda grid from a file")
    print("-d [NSUB]                 Write NA files for specific grain sizes")
    print("-s [NANG]                 Add scattering matrix for NANG angles to output")
    print("-chop [NDEG]              Remove NDEG degrees from the forward-scattering peak")
    print("-o [DIRECTORY]            Output to DIRECTORY instead of current working dir")
    print("-radmc [LABEL]            Output as RADMC-3D input file")
    print("-fits; -print [Var]       Output to FITS file, or to STDOUT")
    print("-h [OPT]; -man            Show this msg or help on -OPT; Show the full manual")
    print("-q; -v                    Quiet or more verbose on STDOUT")
    print("-xlim XLIM                Switch to Mie for speed at x=XLIM")
    print("===============================================================================")


def list_materials():
    print(":===================== *** LIST OF BUILT-IN MATERIALS *** =====================:")
    print(": amorph.pyroxenes  pyr-mg100/95/80/70/60/50/40                                :")
    print(": amorph.olivines   ol-mg100/40                        (Dorschner95,Henning96) :")
    print(": cryst. pyr/ol     pyr-c-mg96 ol-c-mg100/95/00      (Jäger96,Suto06,Fabian01) :")
    print(": other silicates   astrosil                                        (Draine03) :")
    print(": amorphous carbon  c-z    c-p                           (Zubko96,Preibisch93) :")
    print(": graphite,special  c-gra  c-nano  c-org                (Dra.03,Mut.04,Hen.96) :")
    print(": quartz,corundum   sio2   cor-c                          (Kitamura07,Koike95) :")
    print(": iron/sulfide      fe-c   fes                                     (Henning96) :")
    print(": carbides          sic                                             (Draine93) :")
    print(": water ice         h2o-w  h2o-a                          (Warren08,Hudgins93) :")
    print(": other ices        co2-w  nh3-m                       (Warren86,Martonchik83) :")
    print(":                   co-a   co2-a/c ch4-a/c ch3oh-a/c   (Palumbo06,Gerakines20) :")
    print(":                                                                              :")
    print(": *** ABBREVIATIONS AND GENERIC KEYS FOR QUICK ACCESS ***                      :")
    print(": pyr  -> pyr-mg70     c    -> c-z         iron -> fe-c      h2o  -> h2o-w     :")
    print(": ol   -> ol-mg50      gra  -> c-gra       qua  -> sio2      co   -> co-a      :")
    print(": ens  -> pyr-c-mg96   org  -> c-org       cor  -> cor-c     co2  -> co2-w     :")
    print(": for  -> ol-c-mg100                       tro  -> fes       nh3  -> nh3-m     :")
    print(": fay  -> ol-c-mg00                                                            :")
    print("================================================================================")
